version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb://mongo:27017/afyasmart
    depends_on:
      - mongo
    networks:
      - afyasmart-net

  mongo:
    image: mongo:6.0
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - afyasmart-net

volumes:
  mongo-data:

networks:
  afyasmart-net:

